---
#
# Ansible managed
#
repository:
  description: Role for installing Apache Maven.
  homepage: https://buluma.github.io/
  topics: maven, mvn, java, development, ansible, molecule, tox, playbook, hacktoberfest
