---
#
# Ansible managed
#
repository:
  description: Install and configure Apache Maven on your systems.
  homepage: https://buluma.github.io/
  topics: maven, mvn, java, development, ansible, molecule, tox, playbook
