---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_pkg_mgr == "apt"

    # - name: install jdk 8 (apt)
    #   become: yes
    #   ansible.builtin.apt:
    #     name: openjdk-8-jdk
    #     state: present
    #   when: ansible_os_family == 'Ubuntu'

  roles:
    - role: buluma.maven
      maven_version: '3.8.5'
      maven_install_dir: /opt/maven

    - role: buluma.maven
      maven_version: '3.3.9'
      maven_is_default_installation: no
      maven_fact_group_name: maven_3_3

  post_tasks:
    - name: verify default maven facts
      ansible.builtin.assert:
        that:
          - ansible_local.maven.general.version is defined
          - ansible_local.maven.general.home is defined

    - name: verify maven 3.3 facts
      ansible.builtin.assert:
        that:
          - ansible_local.maven_3_3.general.version is defined
          - ansible_local.maven_3_3.general.home is defined
