---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
      changed_when: no

    - name: install jre-headless 8
      become: yes
      ansible.builtin.apt:
        name: openjdk-8-jre-headless
        state: present

  roles:
    - role: buluma.maven
      maven_version: '3.8.5'
      maven_install_dir: /opt/maven

  post_tasks:
    - name: verify default maven facts
      ansible.builtin.assert:
        that:
          - ansible_local.maven.general.version is defined
          - ansible_local.maven.general.home is defined
